---
abstract: 'asyncronously check remote host for reachability'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires:
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-Ping
requires:
  Future: 0
  IO::Async: 0.61
  Module::Runtime: 0
  Moo: 1
  Time::HiRes: 0
  namespace::clean: 0.23
  perl: 5.010
resources:
  bugtracker: https://github.com/frioux/Net-Async-Ping/issues
  homepage: https://github.com/frioux/Net-Async-Ping
  repository: https://github.com/frioux/Net-Async-Ping.git
version: 0.001000
